version: "3.9"

services:
  web:
    container_name: "demo_web"
    image: rails7
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    tty: true
  postgres:
    container_name: "demo_postgres"
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
  redis:
    container_name: "demo_redis"
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server

